library(data.table)
library(dplyr)
library(optparse)

# Load arguments ----------------------------------------------------------
# Environment: R 3.6.1
args <- commandArgs(trailingOnly = FALSE)

parse <- OptionParser()

option_list <- list(
   make_option('--exposure', type='character', help="Intermediate files for exposure data", action='store'),
   make_option('--outcomeName', type='character', help='Name of outcome phenotype', action='store'),
   make_option('--summout', type='character', help="Summary stats for outcome", action='store'),
   make_option('--interout', type='character', help='Folder for intermediate files generated by processing outcome data', action='store')
)

args = commandArgs(trailingOnly=TRUE)

opt <- parse_args(OptionParser(option_list=option_list), args=args)
exposure.path=opt$exposure
summ.outcome=opt$summout
outcome.name=opt$outcomeName
output.path=opt$interout


# Basic settings ----------------------------------------------------------

dir.create(file.path(output.path), showWarnings = FALSE)

# Load outcome data -------------------------------------------------------

outcome.summstats=fread(summ.outcome,header=T,stringsAsFactors=F) %>%
      select(SNP,A1,A2,BETA,SE,P,Direction,af=Freq1,CHR,BP)

# Process outcome data ----------------------------------------------------

ls.exposure=list.files(path = exposure.path, pattern = '.exposure_dat') %>% gsub('.exposure_dat','',.) 
ls.exposure.filename = list.files(path = exposure.path, pattern = '.exposure_dat',full.names=T)

# Match with the first exposure data
f = 1
traitA='multivar'
traitB=outcome.name

## exposure dat
exposure.dat=fread(ls.exposure.filename[f],header=T,stringsAsFactors=F)
 
## outcome dat
count.instrument = sum(outcome.summstats$SNP %in% exposure.dat$SNP)
if (count.instrument>=5){
   outcome_match=outcome.summstats[outcome.summstats$SNP %in% exposure.dat$SNP,] %>%
      dplyr::select(SNP,A1,A2,af,BETA,SE,P,Direction)
   colnames(outcome_match)=c("SNP","effect_allele","other_allele","eaf","beta","se","pval",'direction')
   outcome_match$Phenotype=traitB
   outcome_match$samplesize=807553
   
   write.table(outcome_match,
               file=paste0(output.path,'/',traitA,".outcome_dat"),
               col.names=T,row.names = F,sep="\t",quot=F)
   system(paste0('echo ',dim(outcome_match),' ','Outcome for ',traitA,' prep   done >> XS.log'))
}


rm(list=ls())